/**
 * Mock/Fallback Data for Strapi CMS
 *
 * Used when the CMS is offline, unreachable, or returns empty data.
 * This ensures the frontend always has content to display.
 *
 * Rules: integate-rule.md §6
 */

import type {
  GlobalSetting,
  FooterSetting,
  Product,
  Category,
  Brand,
  Article,
  BlogPage,
  AboutPage,
  ContactPage,
  FreeTrial,
  PrivacyPolicy,
  PrivacyRequest,
  PdpaSetting,
  TermsOfService,
  CookiePolicy,
  CookieCategory,
  CookieSetting,
  DownloadItem,
  DownloadsPage,
  SoftwareRelease,
  ContactFloating,
  Navigation,
  Homepage,
  ProductsServices,
  SupportPage,
} from "./strapi";


// ─── Branded placeholder image URLs ────────────────────────────────

const IMG = {
  productWax: "https://placehold.co/800x600/fef3c7/b45309?text=Ribbon+Wax",
  productWaxResin:
    "https://placehold.co/800x600/dbafe/1e40af?text=Wax-Resin",
  productResin:
    "https://placehold.co/800x600/dcfce7/166534?text=Resin+Ribbon",
  article: "https://placehold.co/1200x630/017fe4/ffffff?text=Ryhts+Article",
  category: "https://placehold.co/400x300/f0f4ff/017fe4?text=Category",
  logo: "https://placehold.co/200x80/017fe4/ffffff?text=RYHTS",
  og: "https://placehold.co/1200x630/017fe4/ffffff?text=Ryhts+Ribbon",
};

const FILE = {
  guide: "/downloads/ryhts-ribbon-guide.pdf",
  catalog: "/downloads/ryhts-product-catalog.pdf",
  spec: "/downloads/ryhts-ribbon-specification.pdf",
  installer: "/downloads/istock-express-installer.zip",
};

// ─── Mock Brands ───────────────────────────────────────────────────

export const mockBrands: Brand[] = [
  {
    id: 1,
    documentId: "mock-brand-1",
    name: "Ricoh",
    slug: "ricoh",
    logo: { id: 101, name: "ricoh-logo.png", url: IMG.logo, alternativeText: "Ricoh" },
    description: "High-quality thermal transfer ribbons from Ricoh.",
    products: [],
  },
  {
    id: 2,
    documentId: "mock-brand-2",
    name: "CSoft",
    slug: "csoft",
    logo: { id: 102, name: "csoft-logo.png", url: IMG.logo, alternativeText: "CSoft" },
    description: "CSoft ribbons offer premium printing solutions.",
    products: [],
  },
  {
    id: 3,
    documentId: "mock-brand-3",
    name: "Armor",
    slug: "armor",
    logo: { id: 103, name: "armor-logo.png", url: IMG.logo, alternativeText: "Armor" },
    description: "ARMOR AXR thermal transfer ribbons — European quality.",
    products: [],
  },
];

// ─── Mock Categories ───────────────────────────────────────────────

export const mockCategories: Category[] = [
  {
    id: 1,
    documentId: "mock-cat-1",
    name: "Ribbon Wax",
    slug: "ribbon-wax",
    description: "ริบบอนแบบ Wax เหมาะสำหรับการพิมพ์บาร์โค้ดทั่วไป",
    image: { id: 201, name: "wax.png", url: IMG.category, alternativeText: "Ribbon Wax" },
    products: [],
  },
  {
    id: 2,
    documentId: "mock-cat-2",
    name: "Ribbon Wax-Resin",
    slug: "ribbon-wax-resin",
    description: "ริบบอนแบบ Wax-Resin ผสมผสานความคุ้มค่าของ Wax กับความทนทานของ Resin",
    image: { id: 202, name: "wax-resin.png", url: IMG.category, alternativeText: "Ribbon Wax-Resin" },
    products: [],
  },
  {
    id: 3,
    documentId: "mock-cat-3",
    name: "Ribbon Resin",
    slug: "ribbon-resin",
    description: "ริบบอนแบบ Resin ทนทานสูงสุด",
    image: { id: 203, name: "resin.png", url: IMG.category, alternativeText: "Ribbon Resin" },
    products: [],
  },
];

// ─── Mock Products ─────────────────────────────────────────────────

export const mockProducts: Product[] = [
  {
    id: 1,
    documentId: "mock-prod-1",
    title: "Ribbon Wax Premium 110x300",
    slug: "ribbon-wax-premium-110x300",
    description: "<p>ริบบอน Wax คุณภาพสูง ขนาด 110mm x 300m</p>",
    shortDescription: "ริบบอน Wax คุณภาพสูง ขนาด 110x300mm",
    price: 350,
    ribbonType: "wax",
    sizes: ["110mm x 300m", "80mm x 300m"],
    compatibility: "Zebra, TSC, SATO, Honeywell",
    isFeatured: true,
    images: [{ id: 301, name: "wax.jpg", url: IMG.productWax, alternativeText: "Ribbon Wax Premium" }],
    brand: mockBrands[0],
    categories: [mockCategories[0]],
    publishedAt: "2025-01-15T10:00:00.000Z",
  },
  {
    id: 2,
    documentId: "mock-prod-2",
    title: "Ribbon Wax-Resin Premium 110x300",
    slug: "ribbon-wax-resin-premium-110x300",
    description: "<p>ริบบอน Wax-Resin คุณภาพสูง</p>",
    shortDescription: "ริบบอน Wax-Resin คุณภาพสูง ทนทานต่อแสง UV",
    price: 550,
    ribbonType: "wax_resin",
    sizes: ["110mm x 300m"],
    compatibility: "Zebra, TSC, SATO",
    isFeatured: true,
    images: [{ id: 302, name: "wax-resin.jpg", url: IMG.productWaxResin, alternativeText: "Ribbon Wax-Resin" }],
    brand: mockBrands[1],
    categories: [mockCategories[1]],
    publishedAt: "2025-01-20T10:00:00.000Z",
  },
  {
    id: 3,
    documentId: "mock-prod-3",
    title: "Ribbon Resin Premium 110x300",
    slug: "ribbon-resin-premium-110x300",
    description: "<p>ริบบอน Resin คุณภาพสูงสุด</p>",
    shortDescription: "ริบบอน Resin ทนทานสูงสุด สำหรับงานอุตสาหกรรม",
    price: 850,
    ribbonType: "resin",
    sizes: ["110mm x 300m"],
    compatibility: "Zebra, TSC, SATO, Honeywell",
    isFeatured: true,
    images: [{ id: 303, name: "resin.jpg", url: IMG.productResin, alternativeText: "Ribbon Resin" }],
    brand: mockBrands[2],
    categories: [mockCategories[2]],
    publishedAt: "2025-02-01T10:00:00.000Z",
  },
  {
    id: 4,
    documentId: "mock-prod-4",
    title: "Ribbon Wax Economy 80x300",
    slug: "ribbon-wax-economy-80x300",
    description: "<p>ริบบอน Wax ราคาประหยัด</p>",
    shortDescription: "ริบบอน Wax ราคาประหยัด ขนาด 80x300mm",
    price: 250,
    ribbonType: "wax",
    sizes: ["80mm x 300m"],
    compatibility: "Zebra, TSC",
    isFeatured: false,
    images: [{ id: 304, name: "wax-econ.jpg", url: IMG.productWax, alternativeText: "Ribbon Wax Economy" }],
    brand: mockBrands[0],
    categories: [mockCategories[0]],
    publishedAt: "2025-02-10T10:00:00.000Z",
  },
  {
    id: 5,
    documentId: "mock-prod-5",
    title: "Ribbon Wax-Resin Industrial 110x450",
    slug: "ribbon-wax-resin-industrial-110x450",
    description: "<p>ริบบอน Wax-Resin อุตสาหกรรม</p>",
    shortDescription: "ริบบอน Wax-Resin อุตสาหกรรม ขนาด 110x450mm",
    price: 750,
    ribbonType: "wax_resin",
    sizes: ["110mm x 450m"],
    compatibility: "Zebra ZT series",
    isFeatured: false,
    images: [{ id: 305, name: "wax-resin-ind.jpg", url: IMG.productWaxResin, alternativeText: "Ribbon Wax-Resin Industrial" }],
    brand: mockBrands[1],
    categories: [mockCategories[1]],
    publishedAt: "2025-02-15T10:00:00.000Z",
  },
  {
    id: 6,
    documentId: "mock-prod-6",
    title: "Ribbon Resin Chemical Resistant 110x300",
    slug: "ribbon-resin-chemical-resistant-110x300",
    description: "<p>ริบบอน Resin ทนสารเคมี</p>",
    shortDescription: "ริบบอน Resin ทนสารเคมี สำหรับงานโรงงาน",
    price: 950,
    ribbonType: "resin",
    sizes: ["110mm x 300m"],
    compatibility: "Zebra ZT series, Honeywell PM series",
    isFeatured: false,
    images: [{ id: 306, name: "resin-chem.jpg", url: IMG.productResin, alternativeText: "Ribbon Resin Chemical" }],
    brand: mockBrands[2],
    categories: [mockCategories[2]],
    publishedAt: "2025-03-01T10:00:00.000Z",
  },
];

// ─── Mock Articles ─────────────────────────────────────────────────

export const mockArticlesByLocale: Record<"th" | "en", Article[]> = {
  th: [
    {
      id: 1,
      documentId: "mock-art-1",
      title: "วิธีเลือกริบบอนให้เหมาะกับเครื่องพิมพ์ของคุณ",
      slug: "how-to-choose-ribbon-for-your-printer",
      content: "<h2>ริบบอนมีกี่แบบ?</h2><p>ริบบอนมี 3 ประเภท: Wax, Wax-Resin, Resin</p>",
      excerpt: "เรียนรู้วิธีเลือกริบบอนให้เหมาะสมกับเครื่องพิมพ์และวัสดุฉลากของคุณ",
      featuredImage: { id: 401, name: "choose-ribbon.jpg", url: IMG.article, alternativeText: "วิธีเลือกริบบอน" },
      author: "Ryhts Team",
      articleDate: "2026-08-01",
      tags: ["ริบบอน", "บาร์โค้ด"],
      views: 156,
      category: mockCategories[0],
      publishedAt: "2026-08-01T10:00:00.000Z",
    },
    {
      id: 2,
      documentId: "mock-art-2",
      title: "เช็กลิสต์ก่อนสั่งซื้อริบบอนสำหรับโรงงาน",
      slug: "barcode-ribbon-ordering-checklist",
      content: "<p>ข้อมูลที่ควรเตรียมก่อนสั่งซื้อริบบอน</p>",
      excerpt: "เตรียมรุ่นเครื่องพิมพ์ ขนาดริบบอน และชนิดฉลากให้พร้อมก่อนขอใบเสนอราคา",
      featuredImage: { id: 402, name: "ordering-checklist.jpg", url: IMG.article, alternativeText: "เช็กลิสต์สั่งซื้อริบบอน" },
      author: "Ryhts Team",
      articleDate: "2026-08-08",
      tags: ["คู่มือ", "สั่งซื้อ"],
      views: 89,
      category: mockCategories[1],
      publishedAt: "2026-08-08T10:00:00.000Z",
    },
    {
      id: 3,
      documentId: "mock-art-3",
      title: "เทคนิคการเก็บรักษาริบบอนให้พิมพ์คมชัด",
      slug: "tips-for-ribbon-maintenance",
      content: "<p>เทคนิคดูแลริบบอนให้ใช้งานได้นาน</p>",
      excerpt: "วิธีเก็บริบบอนให้ห่างจากความชื้น ความร้อน และแสงแดดเพื่อรักษาคุณภาพงานพิมพ์",
      featuredImage: { id: 403, name: "maintenance.jpg", url: IMG.article, alternativeText: "เทคนิคดูแลริบบอน" },
      author: "Ryhts Team",
      articleDate: "2026-08-15",
      tags: ["เทคนิค", "การดูแล"],
      views: 67,
      category: mockCategories[2],
      publishedAt: "2026-08-15T10:00:00.000Z",
    },
  ],
  en: [
    {
      id: 11,
      documentId: "mock-art-en-1",
      title: "How to choose the right ribbon for your barcode printer",
      slug: "how-to-choose-ribbon-for-your-printer",
      content: "<h2>Ribbon types</h2><p>Barcode printer ribbons commonly use Wax, Wax-Resin, or Resin grades.</p>",
      excerpt: "A practical guide to matching ribbon grade with your printer, label material, and work environment.",
      featuredImage: { id: 411, name: "choose-ribbon-en.jpg", url: IMG.article, alternativeText: "How to choose ribbon" },
      author: "Ryhts Team",
      articleDate: "2026-08-01",
      tags: ["ribbon", "barcode"],
      views: 156,
      category: mockCategories[0],
      publishedAt: "2026-08-01T10:00:00.000Z",
    },
    {
      id: 12,
      documentId: "mock-art-en-2",
      title: "Pre-order checklist for industrial barcode ribbons",
      slug: "barcode-ribbon-ordering-checklist",
      content: "<p>Information to prepare before ordering barcode ribbons.</p>",
      excerpt: "Prepare printer model, ribbon width, core size, and label material before requesting a quote.",
      featuredImage: { id: 412, name: "ordering-checklist-en.jpg", url: IMG.article, alternativeText: "Ribbon ordering checklist" },
      author: "Ryhts Team",
      articleDate: "2026-08-08",
      tags: ["guide", "ordering"],
      views: 89,
      category: mockCategories[1],
      publishedAt: "2026-08-08T10:00:00.000Z",
    },
    {
      id: 13,
      documentId: "mock-art-en-3",
      title: "Storage tips for sharper thermal transfer printing",
      slug: "tips-for-ribbon-maintenance",
      content: "<p>How to store ribbons for long-lasting print quality.</p>",
      excerpt: "Keep ribbons away from humidity, heat, and direct sunlight to preserve print quality.",
      featuredImage: { id: 413, name: "maintenance-en.jpg", url: IMG.article, alternativeText: "Ribbon storage tips" },
      author: "Ryhts Team",
      articleDate: "2026-08-15",
      tags: ["tips", "maintenance"],
      views: 67,
      category: mockCategories[2],
      publishedAt: "2026-08-15T10:00:00.000Z",
    },
  ],
};

export const mockArticles: Article[] = mockArticlesByLocale.th;

// ─── Mock Blog Page ───────────────────────────────────────────────

export const mockBlogPage: Record<"th" | "en", BlogPage> = {
  th: {
    heroSection: {
      badge: "บทความ",
      title: "บทความและข่าวสารจาก Ryhts",
      description:
        "ติดตามคำแนะนำการเลือกริบบอน เทคนิคงานพิมพ์บาร์โค้ด และข่าวสารสินค้าสำหรับธุรกิจที่ต้องการงานพิมพ์คมชัดและเชื่อถือได้",
    },
    listingSection: {
      breadcrumbLabel: "บทความ",
      emptyTitle: "ยังไม่มีบทความในขณะนี้",
      emptyDescription: "กลับมาใหม่อีกครั้งเพื่ออ่านข่าวสารและคู่มือจาก Ryhts",
      offlineTitle: "ไม่สามารถโหลดบทความได้",
      offlineMessage: "กรุณาตรวจสอบการเชื่อมต่อและลองอีกครั้ง",
    },
    featuredPosts: mockArticlesByLocale.th,
    seo: {
      metaTitle: "บทความและข่าวสาร | Ryhts",
      metaDescription: "บทความ คู่มือ และข่าวสารเกี่ยวกับริบบอนและงานพิมพ์บาร์โค้ดจาก Ryhts",
      ogType: "website",
      schemaType: "CollectionPage",
    },
  },
  en: {
    heroSection: {
      badge: "Articles",
      title: "Ryhts articles and updates",
      description:
        "Read practical ribbon selection guides, barcode printing tips, and product updates for reliable label production.",
    },
    listingSection: {
      breadcrumbLabel: "Articles",
      emptyTitle: "No articles available yet",
      emptyDescription: "Check back later for Ryhts news, guides, and product updates.",
      offlineTitle: "Unable to load articles",
      offlineMessage: "Please check your connection and try again.",
    },
    featuredPosts: mockArticlesByLocale.en,
    seo: {
      metaTitle: "Articles & Updates | Ryhts",
      metaDescription: "Articles, guides, and updates about thermal transfer ribbons and barcode printing from Ryhts.",
      ogType: "website",
      schemaType: "CollectionPage",
    },
  },
};

// ─── Mock Pages (legacy) ───────────────────────────────────────────

export const mockPages: Record<string, { title: string; slug: string; content: string }> = {
  "about-ryhts": { title: "เกี่ยวกับ Ryhts", slug: "about-ryhts", content: "" },
  "contact-us": { title: "ติดต่อเรา", slug: "contact-us", content: "" },
};

// ─── Mock Single Types ─────────────────────────────────────────────

export const mockGlobalSetting: Record<"th" | "en", GlobalSetting> = {
  th: {
    siteName: "RYHTS",
    siteLogo: { id: 501, name: "logo.png", url: IMG.logo, alternativeText: "Ryhts Ribbon" },
    contactInfo: {
      companyName: "บริษัท ไรต์ส จำกัด",
      address: "กรุงเทพมหานคร ประเทศไทย",
      phone: "094-624-6649",
      email: "sales@ryhts.com",
      businessHours: "จันทร์-ศุกร์ 09:00-18:00 น.",
      mapUrl: "",
      socialLinks: {
        facebook: "https://www.facebook.com/RyhtsRibbon",
        line: "https://lin.ee/xnw0e2Y",
      },
    },
    stats: [
      { label: "ลูกค้าที่ไว้วางใจ", value: "257+", sortOrder: 1 },
      { label: "ขนาดสินค้า", value: "100+", sortOrder: 2 },
    ],
    seoConfig: {
      siteUrl: "https://ryhts.com",
      siteName: "Ryhts Ribbon",
      defaultTitle: "RYHTS - ริบบอนคุณภาพสำหรับเครื่องพิมพ์บาร์โค้ด",
      defaultDescription: "Ryhts จำหน่ายริบบอน Wax, Wax-Resin และ Resin สำหรับเครื่องพิมพ์บาร์โค้ด พร้อมคำแนะนำจากทีมงาน",
      brandName: "Ryhts Ribbon",
      facebookUrl: "https://www.facebook.com/RyhtsRibbon",
      lineUrl: "https://lin.ee/xnw0e2Y",
      googleAnalyticsId: "",
      facebookPixelId: "",
      twitterHandle: "",
    },
  },
  en: {
    siteName: "RYHTS",
    siteLogo: { id: 502, name: "logo-en.png", url: IMG.logo, alternativeText: "Ryhts Ribbon" },
    contactInfo: {
      companyName: "Ryhts Co., Ltd.",
      address: "Bangkok, Thailand",
      phone: "094-624-6649",
      email: "sales@ryhts.com",
      businessHours: "Monday-Friday 09:00-18:00",
      mapUrl: "",
      socialLinks: {
        facebook: "https://www.facebook.com/RyhtsRibbon",
        line: "https://lin.ee/xnw0e2Y",
      },
    },
    stats: [
      { label: "Trusted clients", value: "257+", sortOrder: 1 },
      { label: "Product sizes", value: "100+", sortOrder: 2 },
    ],
    seoConfig: {
      siteUrl: "https://ryhts.com",
      siteName: "Ryhts Ribbon",
      defaultTitle: "RYHTS - Premier Ribbons for Barcode Printers",
      defaultDescription: "Ryhts supplies Wax, Wax-Resin, and Resin ribbons for barcode printers with practical support from our team.",
      brandName: "Ryhts Ribbon",
      facebookUrl: "https://www.facebook.com/RyhtsRibbon",
      lineUrl: "https://lin.ee/xnw0e2Y",
      googleAnalyticsId: "",
      facebookPixelId: "",
      twitterHandle: "",
    },
  },
};

export const mockFooterSetting: FooterSetting = {
  ctaBadge: "รับข่าวสาร",
  ctaTitle: "กดรับสมัครข่าวสารจากเรา",
  ctaDescription: "สมัครรับข่าวสารและติดตามสินค้าออกใหม่",
  primaryCtaLabel: "สมัครรับข่าวสาร",
  primaryCtaUrl: "#",
  secondaryCtaLabel: "ติดต่อฝ่ายขาย Ryhts",
  secondaryCtaUrl: "https://lin.ee/xnw0e2Y",
  stats: [],
  companyDescription:
    "จำหน่ายริบบอนหรือผ้าหมึกพิมพ์สำหรับใช้กับเครื่องพิมพ์บาร์โค้ดทุกขนาด มีให้ท่านเลือกใช้หลายชนิด\nไรต์ส (ryhts) เรามุ่งมั่นที่จะพัฒนาสินค้านำเข้าที่ได้มาตรฐาน และให้บริการที่ตอบโจทย์ ช่วยให้การทำงานของท่านได้สะดวกรวดเร็วและมีประสิทธิภาพที่ดีขึ้น",
  footerSections: [
    {
      title: "Links",
      sortOrder: 1,
      isActive: true,
      links: [
        { label: "Our company", url: "/about/", sortOrder: 1, isActive: true },
        { label: "News", url: "/articles/", sortOrder: 2, isActive: true },
        { label: "Contact Ryhts", url: "/contact/", sortOrder: 3, isActive: true },
      ],
    },
  ],
  legalLinks: [],
  copyright: "All Rights Reserved ©2026 | RYHTS | ryhts.com",
};

export const mockAboutPage: Record<"th" | "en", AboutPage> = {
  th: {
    pageTitle: "เกี่ยวกับ Ryhts",
    pageDescription: "ผู้จำหน่ายริบบอนสำหรับเครื่องพิมพ์บาร์โค้ดที่ช่วยให้ธุรกิจไทยพิมพ์ฉลากได้คมชัดและต่อเนื่อง",
    companyIntro: [
      {
        type: "paragraph",
        children: [
          {
            type: "text",
            text: "Ryhts คัดสรร Ribbon Wax, Wax-Resin และ Resin สำหรับเครื่องพิมพ์บาร์โค้ดหลากหลายรุ่น พร้อมให้คำแนะนำตามวัสดุฉลากและสภาพแวดล้อมการใช้งานจริง",
          },
        ],
      },
    ],
    mission: [
      {
        type: "paragraph",
        children: [
          {
            type: "text",
            text: "เราตั้งใจช่วยให้โรงงาน คลังสินค้า และร้านค้าปลีกเลือกริบบอนได้ตรงรุ่น ลดของเสีย และควบคุมต้นทุนงานพิมพ์ได้ดีขึ้น",
          },
        ],
      },
    ],
    vision: [
      {
        type: "paragraph",
        children: [
          {
            type: "text",
            text: "เป็นทีมที่ลูกค้าไว้วางใจเมื่อต้องการงานพิมพ์บาร์โค้ดที่อ่านง่าย ทนทาน และพร้อมใช้งานในทุกวันทำงาน",
          },
        ],
      },
    ],
    teamTitle: "ทีมงาน Ryhts",
    teamSubtitle: "ทีมฝ่ายขายและซัพพอร์ตที่เข้าใจงานพิมพ์บาร์โค้ดในหน้างานจริง",
    partnerTitle: "เครือข่ายสินค้าและบริการ",
    partnerSubtitle: "ทำงานร่วมกับผู้ผลิตและคู่ค้าด้านเครื่องพิมพ์ ฉลาก และระบบคลังสินค้า",
    timelineTitle: "เส้นทางของเรา",
    timelineSubtitle: "พัฒนาสินค้าและบริการอย่างต่อเนื่องเพื่อรองรับธุรกิจที่ต้องพิมพ์ฉลากทุกวัน",
    seo: {
      metaTitle: "เกี่ยวกับ Ryhts | ริบบอนเครื่องพิมพ์บาร์โค้ด",
      metaDescription: "รู้จัก Ryhts ผู้จำหน่ายริบบอนสำหรับเครื่องพิมพ์บาร์โค้ด พร้อมคำแนะนำสินค้าและบริการสำหรับธุรกิจไทย",
      ogType: "website",
      schemaType: "AboutPage",
    },
  },
  en: {
    pageTitle: "About Ryhts",
    pageDescription: "A barcode printer ribbon supplier helping businesses keep label printing sharp, stable, and cost controlled.",
    companyIntro: [
      {
        type: "paragraph",
        children: [
          {
            type: "text",
            text: "Ryhts supplies Wax, Wax-Resin, and Resin ribbons for a wide range of barcode printers, with practical guidance based on label materials and real operating conditions.",
          },
        ],
      },
    ],
    mission: [
      {
        type: "paragraph",
        children: [
          {
            type: "text",
            text: "Our mission is to help factories, warehouses, and retail teams select the right ribbon grade, reduce reprints, and control printing cost.",
          },
        ],
      },
    ],
    vision: [
      {
        type: "paragraph",
        children: [
          {
            type: "text",
            text: "We aim to be the trusted team for readable, durable barcode labels that are ready for daily business operations.",
          },
        ],
      },
    ],
    teamTitle: "Ryhts Team",
    teamSubtitle: "Sales and support specialists who understand barcode printing workflows.",
    partnerTitle: "Product and service network",
    partnerSubtitle: "Working with printer, label, and warehouse system partners.",
    timelineTitle: "Our Journey",
    timelineSubtitle: "Continuous product and service improvement for teams that print labels every day.",
    seo: {
      metaTitle: "About Ryhts | Barcode Printer Ribbons",
      metaDescription: "Learn about Ryhts, a barcode printer ribbon supplier with product guidance and service support for business printing workflows.",
      ogType: "website",
      schemaType: "AboutPage",
    },
  },
};

export const mockContactPage: Record<"th" | "en", ContactPage> = {
  th: {
    title: "ติดต่อ Ryhts",
    subtitle: "สอบถามสินค้า ขอใบเสนอราคา หรือให้ทีมงานช่วยเลือกริบบอนให้เหมาะกับเครื่องพิมพ์ของคุณ",
    content:
      "<p>ทีม Ryhts พร้อมให้คำแนะนำเกี่ยวกับริบบอน Wax, Wax-Resin และ Resin สำหรับงานพิมพ์บาร์โค้ดทุกประเภท</p>",
    seo: {
      metaTitle: "ติดต่อ Ryhts | ริบบอนเครื่องพิมพ์บาร์โค้ด",
      metaDescription: "ติดต่อฝ่ายขาย Ryhts เพื่อสอบถามสินค้า ขอใบเสนอราคา หรือรับคำแนะนำการเลือกริบบอน",
      ogType: "website",
      schemaType: "ContactPage",
    },
  },
  en: {
    title: "Contact Ryhts",
    subtitle: "Ask about products, request a quote, or let our team recommend the right ribbon for your printer.",
    content:
      "<p>The Ryhts team can help you choose Wax, Wax-Resin, and Resin ribbons for barcode printing workflows.</p>",
    seo: {
      metaTitle: "Contact Ryhts | Barcode Printer Ribbons",
      metaDescription: "Contact Ryhts sales to ask about products, request a quote, or get ribbon selection guidance.",
      ogType: "website",
      schemaType: "ContactPage",
    },
  },
};

export const mockFreeTrial: Record<"th" | "en", FreeTrial> = {
  th: {
    heroBadge: "ทดลองใช้ฟรี",
    heroTitle: "ทดลองใช้บริการแนะนำริบบอน Ryhts ฟรี",
    heroSubtitle:
      "ส่งรายละเอียดเครื่องพิมพ์และฉลากของคุณ ทีม Ryhts จะช่วยประเมินชนิดริบบอน ขนาด และแนวทางทดสอบให้เหมาะกับหน้างานจริง",
    trustItems: [
      { label: "ไม่มีค่าใช้จ่ายเริ่มต้น", sortOrder: 1, isActive: true },
      { label: "ทีมงานช่วยตรวจสเปก", sortOrder: 2, isActive: true },
      { label: "เหมาะกับเครื่องพิมพ์หลายแบรนด์", sortOrder: 3, isActive: true },
    ],
    formBadge: "แบบฟอร์มทดลองใช้",
    formTitle: "ขอคำแนะนำและตัวอย่างทดสอบ",
    formDescription: "กรอกข้อมูลเบื้องต้นเพื่อให้ทีมฝ่ายขายติดต่อกลับพร้อมคำแนะนำที่เหมาะกับงานพิมพ์ของคุณ",
    formLabels: {
      fullNameLabel: "ชื่อ-นามสกุล",
      fullNamePlaceholder: "กรอกชื่อผู้ติดต่อ",
      positionLabel: "ตำแหน่ง",
      positionPlaceholder: "เช่น จัดซื้อ คลังสินค้า ฝ่ายผลิต",
      emailLabel: "อีเมล",
      emailPlaceholder: "name@company.com",
      phoneLabel: "โทรศัพท์",
      phonePlaceholder: "กรอกเบอร์โทรศัพท์",
      companyLabel: "บริษัท",
      companyPlaceholder: "ชื่อบริษัทของคุณ",
      addressLabel: "ที่อยู่",
      addressPlaceholder: "จังหวัดหรือที่อยู่จัดส่ง",
      businessDetailsLabel: "รายละเอียดงานพิมพ์",
      businessDetailsPlaceholder: "แจ้งรุ่นเครื่องพิมพ์ ขนาดริบบอน วัสดุฉลาก และปัญหาที่พบ",
      privacyConsentPrefix: "ฉันยอมรับ",
      privacyPolicyLabel: "นโยบายความเป็นส่วนตัว",
      privacyPolicyUrl: "/privacy-policy/",
      marketingConsentLabel: "ยินยอมรับข่าวสารและข้อเสนอจาก Ryhts",
      submitLabel: "ส่งคำขอทดลองใช้",
      successTitle: "ส่งคำขอสำเร็จ",
      successMessage: "ทีม Ryhts จะติดต่อกลับโดยเร็วที่สุด",
    },
    featuresTitle: "สิ่งที่คุณจะได้รับ",
    features: [
      { title: "คำแนะนำชนิดริบบอน", description: "ช่วยเลือก Wax, Wax-Resin หรือ Resin ให้เหมาะกับวัสดุฉลาก", sortOrder: 1, isActive: true },
      { title: "ตรวจสอบขนาดและแกนม้วน", description: "ลดความเสี่ยงการสั่งซื้อขนาดที่ไม่เข้ากับเครื่องพิมพ์", sortOrder: 2, isActive: true },
      { title: "แนวทางทดสอบก่อนใช้งานจริง", description: "แนะนำการทดสอบความคมชัด ความทนขูดขีด และสภาพแวดล้อม", sortOrder: 3, isActive: true },
    ],
    ctaTitle: "ไม่แน่ใจว่าควรใช้ริบบอนรุ่นไหน?",
    ctaSubtitle: "ส่งข้อมูลมาให้ทีม Ryhts ตรวจสอบก่อนสั่งซื้อจริงได้",
    seo: {
      metaTitle: "ทดลองใช้ฟรีและขอคำแนะนำริบบอน | Ryhts",
      metaDescription: "ขอคำแนะนำริบบอน Wax, Wax-Resin และ Resin สำหรับเครื่องพิมพ์บาร์โค้ดจากทีม Ryhts",
      ogType: "website",
      schemaType: "WebPage",
    },
  },
  en: {
    heroBadge: "Free Trial",
    heroTitle: "Request a free Ryhts ribbon recommendation",
    heroSubtitle:
      "Share your printer and label details so the Ryhts team can recommend the right ribbon type, size, and testing approach for your workflow.",
    trustItems: [
      { label: "No starting cost", sortOrder: 1, isActive: true },
      { label: "Specification support", sortOrder: 2, isActive: true },
      { label: "Compatible with many printer brands", sortOrder: 3, isActive: true },
    ],
    formBadge: "Trial request",
    formTitle: "Request guidance and sample testing",
    formDescription: "Send your basic requirements and our sales team will respond with recommendations for your barcode printing needs.",
    formLabels: {
      fullNameLabel: "Full Name",
      fullNamePlaceholder: "Enter contact name",
      positionLabel: "Position",
      positionPlaceholder: "Purchasing, warehouse, production",
      emailLabel: "Email",
      emailPlaceholder: "name@company.com",
      phoneLabel: "Phone",
      phonePlaceholder: "Enter phone number",
      companyLabel: "Company",
      companyPlaceholder: "Your company name",
      addressLabel: "Address",
      addressPlaceholder: "Province or delivery address",
      businessDetailsLabel: "Printing requirements",
      businessDetailsPlaceholder: "Share printer model, ribbon size, label material, and current issues",
      privacyConsentPrefix: "I agree to the ",
      privacyPolicyLabel: "Privacy Policy",
      privacyPolicyUrl: "/privacy-policy/",
      marketingConsentLabel: "I agree to receive Ryhts news and offers",
      submitLabel: "Submit trial request",
      successTitle: "Request submitted",
      successMessage: "The Ryhts team will contact you shortly.",
    },
    featuresTitle: "What you get",
    features: [
      { title: "Ribbon type recommendation", description: "Match Wax, Wax-Resin, or Resin to your label material.", sortOrder: 1, isActive: true },
      { title: "Size and core check", description: "Reduce the risk of ordering ribbon sizes that do not fit your printer.", sortOrder: 2, isActive: true },
      { title: "Practical testing guidance", description: "Plan tests for print clarity, scratch resistance, and working conditions.", sortOrder: 3, isActive: true },
    ],
    ctaTitle: "Not sure which ribbon to use?",
    ctaSubtitle: "Send your details and the Ryhts team can check before you place an order.",
    seo: {
      metaTitle: "Free Trial and Ribbon Recommendation | Ryhts",
      metaDescription: "Request guidance for Wax, Wax-Resin, and Resin ribbons for barcode printers from the Ryhts team.",
      ogType: "website",
      schemaType: "WebPage",
    },
  },
};

export const mockPrivacyPolicy: Record<"th" | "en", PrivacyPolicy> = {
  th: {
    heroBadge: "นโยบาย",
    heroTitle: "นโยบายความเป็นส่วนตัว",
    heroSubtitle: "แนวทางการเก็บ ใช้ และดูแลข้อมูลส่วนบุคคลของลูกค้า Ryhts",
    lastUpdated: "27 สิงหาคม 2569",
    effectiveDate: "2026-08-27",
    tocTitle: "สารบัญ",
    appliesToTitle: "มีผลกับสินค้าและบริการ",
    sections: [
      {
        title: "ข้อมูลที่เราเก็บรวบรวม",
        content: "<p>เราเก็บข้อมูลติดต่อ ข้อมูลบริษัท รายละเอียดคำขอใบเสนอราคา และข้อมูลการใช้งานเว็บไซต์เท่าที่จำเป็นต่อการให้บริการ</p>",
        sortOrder: 1,
      },
      {
        title: "การใช้ข้อมูล",
        content: "<p>ข้อมูลถูกใช้เพื่อติดต่อกลับ แนะนำสินค้า จัดทำใบเสนอราคา ปรับปรุงบริการ และดูแลความปลอดภัยของระบบ</p>",
        sortOrder: 2,
      },
      {
        title: "สิทธิของเจ้าของข้อมูล",
        content: "<p>ท่านสามารถขอเข้าถึง แก้ไข ลบ จำกัดการใช้ คัดค้าน หรือถอนความยินยอมได้ผ่านแบบฟอร์มคำขอข้อมูลส่วนบุคคล</p>",
        sortOrder: 3,
      },
    ],
    legalContactTitle: "ติดต่อเรื่องข้อมูลส่วนบุคคล",
    legalContactDescription: "หากมีคำถามเกี่ยวกับนโยบายนี้ กรุณาติดต่อทีม Ryhts",
    legalContactInfo: {
      companyName: "Ryhts",
      phone: "094-624-6649",
      email: "sales@ryhts.com",
      businessHours: "จันทร์-ศุกร์ 09:00-18:00",
    },
    relatedLinksTitle: "ลิงก์ที่เกี่ยวข้อง",
    relatedLinks: [
      { label: "คำขอข้อมูลส่วนบุคคล", url: "/privacy-request/", sortOrder: 1, isActive: true },
      { label: "นโยบายคุกกี้", url: "/cookie-policy/", sortOrder: 2, isActive: true },
      { label: "ข้อกำหนดการใช้บริการ", url: "/terms-of-service/", sortOrder: 3, isActive: true },
    ],
    seo: {
      metaTitle: "นโยบายความเป็นส่วนตัว | Ryhts",
      metaDescription: "นโยบายความเป็นส่วนตัวของ Ryhts สำหรับการเก็บ ใช้ และดูแลข้อมูลส่วนบุคคล",
      ogType: "website",
      schemaType: "WebPage",
    },
  },
  en: {
    heroBadge: "Policy",
    heroTitle: "Privacy Policy",
    heroSubtitle: "How Ryhts collects, uses, and protects customer personal data.",
    lastUpdated: "August 27, 2026",
    effectiveDate: "2026-08-27",
    tocTitle: "Contents",
    appliesToTitle: "Applies to products and services",
    sections: [
      {
        title: "Information we collect",
        content: "<p>We collect contact details, company information, quote request details, and website usage information needed to provide our services.</p>",
        sortOrder: 1,
      },
      {
        title: "How we use information",
        content: "<p>Information is used to contact you, recommend products, prepare quotations, improve service quality, and protect our systems.</p>",
        sortOrder: 2,
      },
      {
        title: "Your data rights",
        content: "<p>You may request access, correction, deletion, restriction, objection, or consent withdrawal through our personal data request form.</p>",
        sortOrder: 3,
      },
    ],
    legalContactTitle: "Personal data contact",
    legalContactDescription: "If you have questions about this policy, please contact Ryhts.",
    legalContactInfo: {
      companyName: "Ryhts",
      phone: "094-624-6649",
      email: "sales@ryhts.com",
      businessHours: "Monday-Friday 09:00-18:00",
    },
    relatedLinksTitle: "Related links",
    relatedLinks: [
      { label: "Personal data request", url: "/privacy-request/", sortOrder: 1, isActive: true },
      { label: "Cookie Policy", url: "/cookie-policy/", sortOrder: 2, isActive: true },
      { label: "Terms of Service", url: "/terms-of-service/", sortOrder: 3, isActive: true },
    ],
    seo: {
      metaTitle: "Privacy Policy | Ryhts",
      metaDescription: "Ryhts privacy policy for collecting, using, and protecting personal data.",
      ogType: "website",
      schemaType: "WebPage",
    },
  },
};

export const mockPdpaSetting: PdpaSetting = {
  companyName: "บริษัท ไรต์ส จำกัด",
  dpoName: "Data Protection Officer",
  dpoEmail: "dpo@ryhts.com",
  isActive: true,
};

export const mockTermsOfService: Record<"th" | "en", TermsOfService> = {
  th: {
    heroBadge: "ข้อกำหนด",
    heroTitle: "ข้อกำหนดการใช้บริการ",
    heroSubtitle: "เงื่อนไขการใช้งานเว็บไซต์ การขอใบเสนอราคา และการติดต่อซื้อสินค้ากับ Ryhts",
    lastUpdated: "27 สิงหาคม 2569",
    effectiveDate: "2026-08-27",
    tocTitle: "สารบัญ",
    appliesToTitle: "ใช้กับบริการ",
    sections: [
      {
        title: "การใช้งานเว็บไซต์",
        content: "<p>ผู้ใช้งานควรใช้ข้อมูลบนเว็บไซต์เพื่อประกอบการพิจารณาสินค้า และติดต่อทีมงานเมื่อต้องการยืนยันสเปก ราคา หรือเงื่อนไขจัดส่ง</p>",
        sortOrder: 1,
      },
      {
        title: "ข้อมูลสินค้าและใบเสนอราคา",
        content: "<p>รายละเอียดสินค้า ราคา และระยะเวลาจัดส่งอาจเปลี่ยนแปลงตามรุ่น ขนาด จำนวน และสถานะสินค้าในช่วงเวลาที่ขอใบเสนอราคา</p>",
        sortOrder: 2,
      },
      {
        title: "การติดต่อและการให้บริการ",
        content: "<p>Ryhts จะติดต่อกลับตามข้อมูลที่ลูกค้าให้ไว้ และอาจขอรายละเอียดเพิ่มเติมเพื่อแนะนำริบบอนให้เหมาะกับเครื่องพิมพ์และฉลาก</p>",
        sortOrder: 3,
      },
    ],
    legalContactTitle: "ติดต่อเกี่ยวกับข้อกำหนด",
    legalContactDescription: "สอบถามเงื่อนไขการใช้บริการหรือการสั่งซื้อสินค้าได้ที่ทีม Ryhts",
    legalContactInfo: {
      companyName: "Ryhts",
      phone: "094-624-6649",
      email: "sales@ryhts.com",
      businessHours: "จันทร์-ศุกร์ 09:00-18:00",
    },
    relatedLinksTitle: "ลิงก์ที่เกี่ยวข้อง",
    relatedLinks: [
      { label: "นโยบายความเป็นส่วนตัว", url: "/privacy-policy/", sortOrder: 1, isActive: true },
      { label: "นโยบายคุกกี้", url: "/cookie-policy/", sortOrder: 2, isActive: true },
      { label: "ติดต่อเรา", url: "/contact/", sortOrder: 3, isActive: true },
    ],
    seo: {
      metaTitle: "ข้อกำหนดการใช้บริการ | Ryhts",
      metaDescription: "ข้อกำหนดการใช้เว็บไซต์และบริการของ Ryhts สำหรับการติดต่อ ขอใบเสนอราคา และสั่งซื้อริบบอน",
      ogType: "website",
      schemaType: "WebPage",
    },
  },
  en: {
    heroBadge: "Terms",
    heroTitle: "Terms of Service",
    heroSubtitle: "Terms for using the website, requesting quotations, and contacting Ryhts for products.",
    lastUpdated: "August 27, 2026",
    effectiveDate: "2026-08-27",
    tocTitle: "Contents",
    appliesToTitle: "Applies to services",
    sections: [
      {
        title: "Website usage",
        content: "<p>Website information should be used for product consideration. Please contact our team to confirm specifications, pricing, and delivery conditions.</p>",
        sortOrder: 1,
      },
      {
        title: "Product information and quotations",
        content: "<p>Product details, pricing, and delivery timelines may vary by model, size, quantity, and product availability at the time of quotation.</p>",
        sortOrder: 2,
      },
      {
        title: "Contact and service",
        content: "<p>Ryhts will respond using the information you provide and may request additional details to recommend the right ribbon for your printer and labels.</p>",
        sortOrder: 3,
      },
    ],
    legalContactTitle: "Terms contact",
    legalContactDescription: "Ask Ryhts about service terms or product ordering conditions.",
    legalContactInfo: {
      companyName: "Ryhts",
      phone: "094-624-6649",
      email: "sales@ryhts.com",
      businessHours: "Monday-Friday 09:00-18:00",
    },
    relatedLinksTitle: "Related links",
    relatedLinks: [
      { label: "Privacy Policy", url: "/privacy-policy/", sortOrder: 1, isActive: true },
      { label: "Cookie Policy", url: "/cookie-policy/", sortOrder: 2, isActive: true },
      { label: "Contact Us", url: "/contact/", sortOrder: 3, isActive: true },
    ],
    seo: {
      metaTitle: "Terms of Service | Ryhts",
      metaDescription: "Ryhts website and service terms for contact, quotation requests, and barcode ribbon ordering.",
      ogType: "website",
      schemaType: "WebPage",
    },
  },
};

export const mockCookiePolicy: Record<"th" | "en", CookiePolicy> = {
  th: {
    heroBadge: "นโยบายคุกกี้",
    heroTitle: "นโยบายคุกกี้",
    heroSubtitle: "รายละเอียดประเภทคุกกี้ที่ Ryhts ใช้เพื่อให้เว็บไซต์ทำงานได้ดีและปลอดภัย",
    lastUpdated: "27 สิงหาคม 2569",
    categoriesBadge: "ประเภทคุกกี้",
    categoriesTitle: "คุกกี้ที่เราใช้",
    categoriesDescription: "คุณสามารถจัดการความยินยอมคุกกี้ได้จากแบนเนอร์หรือปุ่มตั้งค่าด้านล่าง",
    categories: [
      {
        title: "คุกกี้จำเป็น",
        description: "ใช้เพื่อให้เว็บไซต์ทำงาน เช่น การจดจำสถานะความยินยอมและความปลอดภัยพื้นฐาน",
        icon: "shield",
        accent: "red",
        sortOrder: 1,
        isActive: true,
      },
      {
        title: "คุกกี้ฟังก์ชัน",
        description: "ช่วยจดจำการตั้งค่าภาษาและประสบการณ์การใช้งานที่เหมาะกับผู้ใช้",
        icon: "settings",
        accent: "orange",
        sortOrder: 2,
        isActive: true,
      },
      {
        title: "คุกกี้วิเคราะห์",
        description: "ช่วยให้เราเข้าใจการใช้งานเว็บไซต์เพื่อนำไปปรับปรุงเนื้อหาและบริการ",
        icon: "analytics",
        accent: "orange",
        sortOrder: 3,
        isActive: true,
      },
      {
        title: "คุกกี้การตลาด",
        description: "ใช้เพื่อวัดผลแคมเปญและนำเสนอข้อมูลสินค้าที่เกี่ยวข้องกับความสนใจ",
        icon: "marketing",
        accent: "red",
        sortOrder: 4,
        isActive: true,
      },
    ],
    sections: [
      {
        title: "คุกกี้คืออะไร",
        content: "<p>คุกกี้คือไฟล์ขนาดเล็กที่เว็บไซต์บันทึกไว้บนอุปกรณ์ของผู้ใช้งาน เพื่อช่วยให้ระบบจดจำการตั้งค่าและให้บริการได้ต่อเนื่อง</p>",
        sortOrder: 1,
      },
      {
        title: "การจัดการคุกกี้",
        content: "<p>ผู้ใช้งานสามารถยอมรับ ปฏิเสธ หรือปรับแต่งคุกกี้เสริมได้ทุกเมื่อผ่านปุ่มจัดการคุกกี้ของเว็บไซต์</p>",
        sortOrder: 2,
      },
    ],
    manageTitle: "จัดการคุกกี้ของคุณ",
    manageDescription: "เปิดหน้าต่างตั้งค่าเพื่อเลือกประเภทคุกกี้ที่อนุญาตให้ Ryhts ใช้งาน",
    manageButtonLabel: "ตั้งค่าคุกกี้",
    backToTopLabel: "กลับขึ้นด้านบน",
    seo: {
      metaTitle: "นโยบายคุกกี้ | Ryhts",
      metaDescription: "นโยบายคุกกี้ของ Ryhts อธิบายประเภทคุกกี้ วัตถุประสงค์ และวิธีจัดการความยินยอม",
      ogType: "website",
      schemaType: "WebPage",
    },
  },
  en: {
    heroBadge: "Cookie Policy",
    heroTitle: "Cookie Policy",
    heroSubtitle: "Details about the cookies Ryhts uses to keep the website useful, reliable, and secure.",
    lastUpdated: "August 27, 2026",
    categoriesBadge: "Cookie Types",
    categoriesTitle: "Cookies We Use",
    categoriesDescription: "You can manage your cookie consent from the banner or the preference button below.",
    categories: [
      {
        title: "Necessary Cookies",
        description: "Used for core website operation, such as consent status and basic security.",
        icon: "shield",
        accent: "red",
        sortOrder: 1,
        isActive: true,
      },
      {
        title: "Functional Cookies",
        description: "Remember language preferences and improve the browsing experience.",
        icon: "settings",
        accent: "orange",
        sortOrder: 2,
        isActive: true,
      },
      {
        title: "Analytics Cookies",
        description: "Help us understand website usage so we can improve content and services.",
        icon: "analytics",
        accent: "orange",
        sortOrder: 3,
        isActive: true,
      },
      {
        title: "Marketing Cookies",
        description: "Used to measure campaigns and provide product information relevant to your interests.",
        icon: "marketing",
        accent: "red",
        sortOrder: 4,
        isActive: true,
      },
    ],
    sections: [
      {
        title: "What cookies are",
        content: "<p>Cookies are small files saved on your device by a website. They help the system remember preferences and provide a consistent service.</p>",
        sortOrder: 1,
      },
      {
        title: "Managing cookies",
        content: "<p>You can accept, reject, or customize optional cookies at any time through the website cookie preference controls.</p>",
        sortOrder: 2,
      },
    ],
    manageTitle: "Manage your cookies",
    manageDescription: "Open preferences to choose which cookie categories Ryhts may use.",
    manageButtonLabel: "Cookie Preferences",
    backToTopLabel: "Back to top",
    seo: {
      metaTitle: "Cookie Policy | Ryhts",
      metaDescription: "Ryhts cookie policy explains cookie categories, purposes, and how to manage consent.",
      ogType: "website",
      schemaType: "WebPage",
    },
  },
};

export const mockCookieCategories: CookieCategory[] = [
  {
    id: 1,
    documentId: "mock-cc-1",
    name: "Necessary",
    slug: "necessary",
    description: "คุกกี้จำเป็นสำหรับการทำงานของเว็บไซต์",
    sortOrder: 0,
    isActive: true,
    isRequired: true,
    isDefaultEnabled: true,
    cookies: [
      { name: "session_id", provider: "Ryhts", purpose: "Session management", duration: "Session", type: "HTTP" },
    ],
    privacyPolicyUrl: "/privacy-policy",
  },
  {
    id: 2,
    documentId: "mock-cc-2",
    name: "Analytics",
    slug: "analytics",
    description: "ช่วยให้เราเข้าใจวิธีการใช้งานเว็บไซต์",
    sortOrder: 1,
    isActive: true,
    isRequired: false,
    isDefaultEnabled: false,
    cookies: [
      { name: "_ga", provider: "Google", purpose: "Analytics", duration: "2 years", type: "HTTP" },
    ],
    privacyPolicyUrl: "/privacy-policy",
  },
  {
    id: 3,
    documentId: "mock-cc-3",
    name: "Marketing",
    slug: "marketing",
    description: "ใช้ในการโฆษณาที่ตรงกับความสนใจ",
    sortOrder: 2,
    isActive: true,
    isRequired: false,
    isDefaultEnabled: false,
    cookies: [
      { name: "_fbp", provider: "Facebook", purpose: "Advertising", duration: "3 months", type: "HTTP" },
    ],
    privacyPolicyUrl: "/privacy-policy",
  },
];

// ─── Mock Products & Services Page ────────────────────────────────

export const mockProductsServices: Record<"th" | "en", ProductsServices> = {
  th: {
    heroBadge: "สินค้าและบริการ",
    heroTitle: "ริบบอนคุณภาพสำหรับงานพิมพ์บาร์โค้ดทุกประเภท",
    heroDescription:
      "Ryhts คัดสรรริบบอน Wax, Wax-Resin และ Resin สำหรับเครื่องพิมพ์บาร์โค้ดทุกขนาด พร้อมคำแนะนำเพื่อให้เหมาะกับหน้างานจริงของคุณ",
    heroPrimaryCtaText: "ปรึกษาฝ่ายขาย",
    heroPrimaryCtaUrl: "/contact/",
    heroSecondaryCtaText: "ดูสินค้า",
    productsBadge: "ผลิตภัณฑ์ Ryhts",
    productsTitle: "เลือกริบบอนให้เหมาะกับงานพิมพ์ของคุณ",
    productsSubtitle:
      "ตัวอย่างสินค้าและบริการสำหรับธุรกิจที่ต้องการงานพิมพ์คมชัด ทนทาน และควบคุมต้นทุนได้ดี",
    products: [
      {
        id: 901,
        documentId: "mock-product-page-wax",
        name: "Ribbon Wax",
        slug: "ribbon-wax",
        pageTitle: "Ribbon Wax",
        shortDesc: "ริบบอน Wax สำหรับงานพิมพ์บาร์โค้ดทั่วไปบนกระดาษและฉลากมาตรฐาน",
        platform: "both",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 902,
        documentId: "mock-product-page-wax-resin",
        name: "Ribbon Wax-Resin",
        slug: "ribbon-wax-resin",
        pageTitle: "Ribbon Wax-Resin",
        shortDesc: "ริบบอน Wax-Resin สำหรับฉลากที่ต้องการความคมชัดและทนการขูดขีดมากขึ้น",
        platform: "both",
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 903,
        documentId: "mock-product-page-resin",
        name: "Ribbon Resin",
        slug: "ribbon-resin",
        pageTitle: "Ribbon Resin",
        shortDesc: "ริบบอน Resin สำหรับงานอุตสาหกรรม ฉลากฟิล์ม และงานที่ต้องทนความร้อนหรือสารเคมี",
        platform: "both",
        sortOrder: 3,
        isActive: true,
      },
    ],
    whyBadge: "ทำไมต้อง Ryhts",
    whyTitle: "พร้อมช่วยเลือกริบบอนที่เหมาะกับเครื่องพิมพ์และฉลากของคุณ",
    whySubtitle:
      "ทีมของเราช่วยดูรุ่นเครื่องพิมพ์ ประเภทฉลาก และสภาพแวดล้อมการใช้งาน เพื่อแนะนำริบบอนที่เหมาะกับต้นทุนและคุณภาพงานพิมพ์",
    whyStats: [
      { value: "3", label: "ประเภทริบบอนหลัก", sortOrder: 1 },
      { value: "100+", label: "ขนาดสินค้า", sortOrder: 2 },
      { value: "พร้อมส่ง", label: "ให้คำปรึกษาและจัดหา", sortOrder: 3 },
    ],
  },
  en: {
    heroBadge: "Products & Services",
    heroTitle: "Quality ribbons for every barcode printing workflow",
    heroDescription:
      "Ryhts supplies Wax, Wax-Resin, and Resin ribbons for barcode printers of all sizes, with practical guidance for real production use.",
    heroPrimaryCtaText: "Contact sales",
    heroPrimaryCtaUrl: "/contact/",
    heroSecondaryCtaText: "View products",
    productsBadge: "Ryhts Products",
    productsTitle: "Choose the right ribbon for your labels",
    productsSubtitle:
      "Sample products and services for businesses that need sharp print quality, durable labels, and controlled operating costs.",
    products: [
      {
        id: 904,
        documentId: "mock-product-page-wax-en",
        name: "Ribbon Wax",
        slug: "ribbon-wax",
        pageTitle: "Ribbon Wax",
        shortDesc: "Wax ribbon for standard barcode printing on paper labels and general-purpose tags.",
        platform: "both",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 905,
        documentId: "mock-product-page-wax-resin-en",
        name: "Ribbon Wax-Resin",
        slug: "ribbon-wax-resin",
        pageTitle: "Ribbon Wax-Resin",
        shortDesc: "Wax-Resin ribbon for clearer output and stronger scratch resistance.",
        platform: "both",
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 906,
        documentId: "mock-product-page-resin-en",
        name: "Ribbon Resin",
        slug: "ribbon-resin",
        pageTitle: "Ribbon Resin",
        shortDesc: "Resin ribbon for industrial labels, film labels, heat resistance, and chemical exposure.",
        platform: "both",
        sortOrder: 3,
        isActive: true,
      },
    ],
    whyBadge: "Why Ryhts",
    whyTitle: "Get the right ribbon for your printer, label, and working conditions",
    whySubtitle:
      "Our team checks your printer model, label material, and usage environment to recommend ribbons that fit both cost and print quality.",
    whyStats: [
      { value: "3", label: "Core ribbon types", sortOrder: 1 },
      { value: "100+", label: "Product sizes", sortOrder: 2 },
      { value: "Ready", label: "Consulting and supply", sortOrder: 3 },
    ],
  },
};

// ─── Mock Homepage ────────────────────────────────────────────────

export const mockHomepage: Record<"th" | "en", Homepage> = {
  th: {
    heroTitle: "Premier Ribbon for Premier Printing",
    heroSubtitle: "ริบบอนคุณภาพสำหรับเครื่องพิมพ์บาร์โค้ด",
    heroDescription:
      "Ryhts จำหน่ายริบบอนหรือผ้าหมึกพิมพ์สำหรับเครื่องพิมพ์บาร์โค้ดทุกขนาด พร้อมทีมงานที่ช่วยแนะนำชนิดริบบอนให้เหมาะกับฉลาก เครื่องพิมพ์ และสภาพแวดล้อมการใช้งานจริง",
    heroCtaText: "ดูสินค้าทั้งหมด",
    heroCtaUrl: "/products/",
    heroCta2Text: "รู้จัก Ryhts",
    heroCta2Url: "/about/",
    heroStats: [
      { value: "15+", label: "ปีประสบการณ์", sortOrder: 1 },
      { value: "500+", label: "ลูกค้าที่ไว้วางใจ", sortOrder: 2 },
      { value: "100+", label: "ขนาดริบบอนพร้อมจัดหา", sortOrder: 3 },
    ],
    featuresTitle: "ทำไมต้องเลือก Ryhts",
    featuresSubtitle: "มุ่งมั่นพัฒนาสินค้านำเข้าที่ได้มาตรฐาน และให้บริการที่ตอบโจทย์หน้างานจริง",
    features: [
      {
        id: 1001,
        documentId: "mock-home-feature-th-1",
        title: "คุณภาพมาตรฐาน",
        description: "คัดสรรริบบอนนำเข้าที่ให้บาร์โค้ดคมชัดและอ่านค่าได้เสถียร",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 1002,
        documentId: "mock-home-feature-th-2",
        title: "ช่วยเลือกสินค้า",
        description: "ทีมงานช่วยตรวจรุ่นเครื่องพิมพ์ วัสดุฉลาก และลักษณะการใช้งานก่อนเสนอสินค้า",
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 1003,
        documentId: "mock-home-feature-th-3",
        title: "จัดหาได้หลายขนาด",
        description: "รองรับริบบอน Wax, Wax-Resin และ Resin สำหรับงานทั่วไปจนถึงอุตสาหกรรม",
        sortOrder: 3,
        isActive: true,
      },
      {
        id: 1004,
        documentId: "mock-home-feature-th-4",
        title: "บริการต่อเนื่อง",
        description: "ดูแลหลังการขายและช่วยแก้ปัญหาคุณภาพงานพิมพ์ให้ธุรกิจทำงานได้ต่อเนื่อง",
        sortOrder: 4,
        isActive: true,
      },
    ],
    productsTitle: "รายการสินค้าขายดีของ Ryhts Ribbon",
    productsSubtitle: "สินค้าริบบอนคุณภาพสูง นำเข้ามาตรฐาน พร้อมให้บริการ",
    products: mockProductsServices.th.products,
    benefitsTitle: "เลือกริบบอนให้ตรงงาน ลดต้นทุนระยะยาว",
    benefitsSubtitle: "Ryhts ช่วยให้ธุรกิจเลือกสเปกได้เหมาะสมตั้งแต่ต้น ลดปัญหางานพิมพ์และเวลาหยุดเครื่อง",
    benefits: [
      {
        id: 1011,
        documentId: "mock-home-benefit-th-1",
        title: "ลดงานพิมพ์เสีย",
        description: "เลือกเกรดริบบอนให้ตรงกับวัสดุฉลากเพื่อให้บาร์โค้ดอ่านง่ายและติดทน",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 1012,
        documentId: "mock-home-benefit-th-2",
        title: "ควบคุมต้นทุนต่อม้วน",
        description: "แนะนำขนาดและชนิดริบบอนให้พอดีกับปริมาณงาน ลดการใช้เกินจำเป็น",
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 1013,
        documentId: "mock-home-benefit-th-3",
        title: "รองรับงานเร่งด่วน",
        description: "มีทีมงานประสานการจัดหาและให้คำแนะนำเพื่อให้ไลน์งานไม่สะดุด",
        sortOrder: 3,
        isActive: true,
      },
    ],
    videoTitle: "ดูภาพรวมการเลือกริบบอน",
    videoSubtitle: "เริ่มจากรุ่นเครื่องพิมพ์ วัสดุฉลาก และความทนทานที่ต้องการ",
    video: {
      id: 1021,
      documentId: "mock-home-video-th",
      title: "แนวทางเลือกริบบอน Ryhts",
      description: "วิดีโอแนะนำปัจจัยหลักก่อนเลือกริบบอนสำหรับเครื่องพิมพ์บาร์โค้ด",
      videoUrl: "https://www.youtube.com/",
      sortOrder: 1,
      isActive: true,
    },
    pricingTitle: "ต้องการใบเสนอราคา?",
    pricingSubtitle: "ติดต่อทีม Ryhts เพื่อรับคำแนะนำและราคาตามขนาดริบบอนที่ต้องการ",
    pricingPlans: [
      {
        id: 1031,
        documentId: "mock-home-pricing-th",
        name: "ปรึกษาและขอใบเสนอราคา",
        slug: "consultation-quote",
        description: "เหมาะสำหรับธุรกิจที่ต้องการเทียบชนิดริบบอนและขนาดก่อนสั่งซื้อ",
        price: "ติดต่อฝ่ายขาย",
        period: "ตามสเปกงาน",
        ctaText: "ติดต่อเรา",
        ctaUrl: "/contact/",
        sortOrder: 1,
        isActive: true,
      },
    ],
    seo: {
      metaTitle: "Ryhts Ribbon | ริบบอนสำหรับเครื่องพิมพ์บาร์โค้ด",
      metaDescription: "Ryhts จำหน่ายริบบอน Wax, Wax-Resin และ Resin สำหรับเครื่องพิมพ์บาร์โค้ดทุกขนาด",
      ogType: "website",
      schemaType: "WebPage",
    },
  },
  en: {
    heroTitle: "Premier Ribbon for Premier Printing",
    heroSubtitle: "Quality ribbons for barcode printers",
    heroDescription:
      "Ryhts supplies thermal transfer ribbons for barcode printers of every size, with practical guidance to match ribbon grade with your labels, printer model, and working conditions.",
    heroCtaText: "View products",
    heroCtaUrl: "/products/",
    heroCta2Text: "About Ryhts",
    heroCta2Url: "/about/",
    heroStats: [
      { value: "15+", label: "Years experience", sortOrder: 1 },
      { value: "500+", label: "Trusted customers", sortOrder: 2 },
      { value: "100+", label: "Ribbon sizes supplied", sortOrder: 3 },
    ],
    featuresTitle: "Why choose Ryhts",
    featuresSubtitle: "Reliable imported ribbon products with support that fits real production needs.",
    features: [
      {
        id: 1101,
        documentId: "mock-home-feature-en-1",
        title: "Consistent quality",
        description: "Selected ribbon grades for sharp barcode output and stable scanning performance.",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 1102,
        documentId: "mock-home-feature-en-2",
        title: "Product guidance",
        description: "Our team checks printer model, label material, and use case before recommending a ribbon.",
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 1103,
        documentId: "mock-home-feature-en-3",
        title: "Multiple sizes",
        description: "Wax, Wax-Resin, and Resin options for general barcode printing through industrial labels.",
        sortOrder: 3,
        isActive: true,
      },
      {
        id: 1104,
        documentId: "mock-home-feature-en-4",
        title: "Ongoing support",
        description: "After-sales help for print quality issues so your operation keeps moving.",
        sortOrder: 4,
        isActive: true,
      },
    ],
    productsTitle: "Best-selling Ryhts Ribbon products",
    productsSubtitle: "Imported ribbon products with reliable quality and practical support.",
    products: mockProductsServices.en.products,
    benefitsTitle: "Match the ribbon to the job and reduce long-term cost",
    benefitsSubtitle: "Ryhts helps teams choose the right specification early, reducing print problems and downtime.",
    benefits: [
      {
        id: 1111,
        documentId: "mock-home-benefit-en-1",
        title: "Reduce failed prints",
        description: "Match ribbon grade with label material so barcodes scan cleanly and stay readable.",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 1112,
        documentId: "mock-home-benefit-en-2",
        title: "Control roll cost",
        description: "Choose suitable ribbon size and grade for actual usage volume.",
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 1113,
        documentId: "mock-home-benefit-en-3",
        title: "Support urgent jobs",
        description: "Our team helps coordinate supply and advice when production timelines are tight.",
        sortOrder: 3,
        isActive: true,
      },
    ],
    videoTitle: "See how to choose a ribbon",
    videoSubtitle: "Start with printer model, label material, and required durability.",
    video: {
      id: 1121,
      documentId: "mock-home-video-en",
      title: "Ryhts ribbon selection guide",
      description: "A quick guide to the main factors before choosing a barcode printer ribbon.",
      videoUrl: "https://www.youtube.com/",
      sortOrder: 1,
      isActive: true,
    },
    pricingTitle: "Need a quotation?",
    pricingSubtitle: "Contact Ryhts for product guidance and pricing based on your ribbon size and use case.",
    pricingPlans: [
      {
        id: 1131,
        documentId: "mock-home-pricing-en",
        name: "Consultation and quote",
        slug: "consultation-quote",
        description: "For teams comparing ribbon type, roll size, and material compatibility before ordering.",
        price: "Contact sales",
        period: "Based on specification",
        ctaText: "Contact us",
        ctaUrl: "/contact/",
        sortOrder: 1,
        isActive: true,
      },
    ],
    seo: {
      metaTitle: "Ryhts Ribbon | Barcode Printer Ribbons",
      metaDescription: "Ryhts supplies Wax, Wax-Resin, and Resin ribbons for barcode printers of every size.",
      ogType: "website",
      schemaType: "WebPage",
    },
  },
};

// ─── Mock Privacy Request Page ────────────────────────────────────

export const mockPrivacyRequest: Record<"th" | "en", PrivacyRequest> = {
  th: {
    settings: {
      heroBadge: "คำขอข้อมูลส่วนบุคคล",
      privacyRequestTitle: "ใช้สิทธิด้านข้อมูลส่วนบุคคลของคุณ",
      privacyRequestDesc:
        "ส่งคำขอเข้าถึง แก้ไข ลบ ระงับการใช้ คัดค้าน หรือถอนความยินยอมเกี่ยวกับข้อมูลส่วนบุคคลที่ Ryhts ดูแลตามกฎหมายคุ้มครองข้อมูลส่วนบุคคล",
      responseTimeLabel: "ระยะเวลาดำเนินการ",
      responseTimeDescription: "ทีมงานจะตรวจสอบและตอบกลับภายใน 30 วันหลังได้รับข้อมูลครบถ้วน",
      secureNoteLabel: "ข้อมูลของคุณปลอดภัย",
      secureNoteDescription: "ข้อมูลในแบบฟอร์มนี้ใช้เพื่อยืนยันตัวตนและดำเนินการตามคำขอเท่านั้น",
      dpoContactLabel: "ติดต่อเจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล",
      phoneLabel: "โทรศัพท์",
      emailLabel: "อีเมล",
      businessHoursLabel: "เวลาทำการ",
      beforeSubmitTitle: "ก่อนส่งคำขอ",
      beforeSubmitDescription: "เตรียมข้อมูลให้ครบเพื่อให้ทีมงานตรวจสอบตัวตนและดำเนินการได้รวดเร็ว",
      beforeSubmitTips: [
        { text: "ใช้ชื่อและอีเมลเดียวกับที่เคยติดต่อ Ryhts", accent: "red", sortOrder: 1, isActive: true },
        { text: "ระบุประเภทคำขอและรายละเอียดข้อมูลที่เกี่ยวข้องให้ชัดเจน", accent: "orange", sortOrder: 2, isActive: true },
        { text: "อย่าส่งเลขบัตรประชาชนหรือเอกสารสำคัญผ่านแบบฟอร์มนี้จนกว่าเจ้าหน้าที่ร้องขอ", accent: "red", sortOrder: 3, isActive: true },
      ],
      formBadge: "แบบฟอร์ม",
      formTitle: "ส่งคำขอข้อมูลส่วนบุคคล",
      requiredFieldsNote: "ช่องที่มีเครื่องหมาย * จำเป็นต้องกรอก",
      formNameLabel: "ชื่อ-นามสกุล *",
      formNamePlaceholder: "ระบุชื่อของคุณ",
      formEmailLabel: "อีเมล *",
      formEmailPlaceholder: "name@example.com",
      formPhoneLabel: "เบอร์โทรศัพท์",
      formPhonePlaceholder: "094-624-6649",
      formCompanyLabel: "บริษัท",
      formCompanyPlaceholder: "ชื่อบริษัทหรือหน่วยงาน",
      formRequestTypeLabel: "ประเภทคำขอ *",
      formRequestTypePlaceholder: "เลือกประเภทคำขอ",
      requestTypes: [
        { value: "access", label: "ขอเข้าถึงข้อมูล", sortOrder: 1, isActive: true },
        { value: "correction", label: "ขอแก้ไขข้อมูล", sortOrder: 2, isActive: true },
        { value: "deletion", label: "ขอลบข้อมูล", sortOrder: 3, isActive: true },
        { value: "restriction", label: "ขอระงับการใช้ข้อมูล", sortOrder: 4, isActive: true },
        { value: "objection", label: "คัดค้านการใช้ข้อมูล", sortOrder: 5, isActive: true },
        { value: "withdrawal", label: "ถอนความยินยอม", sortOrder: 6, isActive: true },
      ],
      formMessageLabel: "รายละเอียดคำขอ *",
      formMessagePlaceholder: "อธิบายข้อมูลหรือการดำเนินการที่ต้องการให้ทีมงานช่วยตรวจสอบ",
      formAdditionalInfoLabel: "ข้อมูลเพิ่มเติม",
      formAdditionalInfoPlaceholder: "ระบุเลขที่ใบเสนอราคา วันที่ติดต่อ หรือข้อมูลอ้างอิงอื่น ๆ ถ้ามี",
      formNote: "หลังส่งแบบฟอร์ม ทีมงานอาจติดต่อกลับเพื่อยืนยันตัวตนก่อนดำเนินการ",
      formSubmitLabel: "ส่งคำขอ",
      formSubmittingLabel: "กำลังส่ง...",
      formSuccessTitle: "ได้รับคำขอแล้ว",
      formSuccessMessage: "ทีมงาน Ryhts จะตรวจสอบและติดต่อกลับตามข้อมูลที่คุณให้ไว้",
      dpoEmail: "dpo@ryhts.com",
      dpoPhone: "094-624-6649",
      legalContactInfo: {
        companyName: "Ryhts",
        address: "ประเทศไทย",
        phone: "094-624-6649",
        email: "dpo@ryhts.com",
        businessHours: "จันทร์ - ศุกร์ 08:30 - 17:30 น.",
      },
    },
    seo: {
      metaTitle: "คำขอข้อมูลส่วนบุคคล | Ryhts",
      metaDescription: "ส่งคำขอใช้สิทธิด้านข้อมูลส่วนบุคคลกับ Ryhts ตามกฎหมาย PDPA",
      ogType: "website",
      schemaType: "ContactPage",
    },
  },
  en: {
    settings: {
      heroBadge: "Personal Data Request",
      privacyRequestTitle: "Exercise your personal data rights",
      privacyRequestDesc:
        "Submit a request to access, correct, delete, restrict, object to, or withdraw consent for personal data handled by Ryhts under privacy law.",
      responseTimeLabel: "Response time",
      responseTimeDescription: "Our team will review and respond within 30 days after receiving complete information.",
      secureNoteLabel: "Your information is protected",
      secureNoteDescription: "Information in this form is used only to verify your identity and process your request.",
      dpoContactLabel: "Contact the Data Protection Officer",
      phoneLabel: "Phone",
      emailLabel: "Email",
      businessHoursLabel: "Business hours",
      beforeSubmitTitle: "Before submitting",
      beforeSubmitDescription: "Prepare enough detail so our team can verify your identity and handle the request efficiently.",
      beforeSubmitTips: [
        { text: "Use the same name and email address you used when contacting Ryhts.", accent: "red", sortOrder: 1, isActive: true },
        { text: "Select the request type and describe the relevant personal data clearly.", accent: "orange", sortOrder: 2, isActive: true },
        { text: "Do not send ID numbers or sensitive documents through this form unless requested by our officer.", accent: "red", sortOrder: 3, isActive: true },
      ],
      formBadge: "Request form",
      formTitle: "Submit a personal data request",
      requiredFieldsNote: "Fields marked with * are required.",
      formNameLabel: "Full name *",
      formNamePlaceholder: "Enter your name",
      formEmailLabel: "Email *",
      formEmailPlaceholder: "name@example.com",
      formPhoneLabel: "Phone",
      formPhonePlaceholder: "094-624-6649",
      formCompanyLabel: "Company",
      formCompanyPlaceholder: "Company or organization name",
      formRequestTypeLabel: "Request type *",
      formRequestTypePlaceholder: "Select request type",
      requestTypes: [
        { value: "access", label: "Access my data", sortOrder: 1, isActive: true },
        { value: "correction", label: "Correct my data", sortOrder: 2, isActive: true },
        { value: "deletion", label: "Delete my data", sortOrder: 3, isActive: true },
        { value: "restriction", label: "Restrict processing", sortOrder: 4, isActive: true },
        { value: "objection", label: "Object to processing", sortOrder: 5, isActive: true },
        { value: "withdrawal", label: "Withdraw consent", sortOrder: 6, isActive: true },
      ],
      formMessageLabel: "Request details *",
      formMessagePlaceholder: "Describe the personal data or action you would like our team to review.",
      formAdditionalInfoLabel: "Additional information",
      formAdditionalInfoPlaceholder: "Add quote number, contact date, or other reference information if available.",
      formNote: "After submission, our team may contact you to verify your identity before processing the request.",
      formSubmitLabel: "Submit request",
      formSubmittingLabel: "Submitting...",
      formSuccessTitle: "Request received",
      formSuccessMessage: "Ryhts will review your request and contact you using the details provided.",
      dpoEmail: "dpo@ryhts.com",
      dpoPhone: "094-624-6649",
      legalContactInfo: {
        companyName: "Ryhts",
        address: "Thailand",
        phone: "094-624-6649",
        email: "dpo@ryhts.com",
        businessHours: "Monday - Friday, 8:30 AM - 5:30 PM",
      },
    },
    seo: {
      metaTitle: "Personal Data Request | Ryhts",
      metaDescription: "Submit a personal data rights request to Ryhts under privacy law.",
      ogType: "website",
      schemaType: "ContactPage",
    },
  },
};

// ─── Mock Downloads Page ──────────────────────────────────────────

export const mockDownloadItemsByLocale: Record<"th" | "en", DownloadItem[]> = {
  th: [
    {
      id: 1201,
      documentId: "mock-download-th-guide",
      title: "คู่มือเลือกริบบอน Ryhts",
      description: "เอกสารแนะนำการเลือก Wax, Wax-Resin และ Resin ให้เหมาะกับฉลากและเครื่องพิมพ์",
      previewUrl: FILE.guide,
      fileSize: "2.4 MB",
      releaseDate: "2026-08-01",
      sortOrder: 1,
      isActive: true,
    },
    {
      id: 1202,
      documentId: "mock-download-th-catalog",
      title: "แคตตาล็อกสินค้า Ryhts Ribbon",
      description: "รายการสินค้าและขนาดริบบอนตัวอย่างสำหรับเครื่องพิมพ์บาร์โค้ดหลายแบรนด์",
      previewUrl: FILE.catalog,
      fileSize: "5.8 MB",
      releaseDate: "2026-08-05",
      sortOrder: 2,
      isActive: true,
    },
    {
      id: 1203,
      documentId: "mock-download-th-spec",
      title: "ตารางสเปกริบบอนสำหรับงานอุตสาหกรรม",
      description: "ข้อมูลเปรียบเทียบความทนความร้อน สารเคมี และวัสดุฉลากที่แนะนำ",
      previewUrl: FILE.spec,
      fileSize: "1.9 MB",
      releaseDate: "2026-08-10",
      sortOrder: 3,
      isActive: true,
    },
  ],
  en: [
    {
      id: 1211,
      documentId: "mock-download-en-guide",
      title: "Ryhts ribbon selection guide",
      description: "A practical guide to choosing Wax, Wax-Resin, and Resin ribbons for your labels and printer.",
      previewUrl: FILE.guide,
      fileSize: "2.4 MB",
      releaseDate: "2026-08-01",
      sortOrder: 1,
      isActive: true,
    },
    {
      id: 1212,
      documentId: "mock-download-en-catalog",
      title: "Ryhts Ribbon product catalog",
      description: "Product list and sample ribbon sizes for common barcode printer brands.",
      previewUrl: FILE.catalog,
      fileSize: "5.8 MB",
      releaseDate: "2026-08-05",
      sortOrder: 2,
      isActive: true,
    },
    {
      id: 1213,
      documentId: "mock-download-en-spec",
      title: "Industrial ribbon specification table",
      description: "Comparison data for heat resistance, chemical resistance, and recommended label materials.",
      previewUrl: FILE.spec,
      fileSize: "1.9 MB",
      releaseDate: "2026-08-10",
      sortOrder: 3,
      isActive: true,
    },
  ],
};

export const mockSoftwareReleasesByLocale: Record<"th" | "en", SoftwareRelease[]> = {
  th: [
    {
      id: 1221,
      documentId: "mock-release-th-latest",
      name: "iStock Express Installer",
      version: "2026.8",
      releaseDate: "2026-08-15",
      summary: "เวอร์ชันตัวอย่างสำหรับหน้าดาวน์โหลด พร้อมปรับปรุงความเสถียรและเอกสารช่วยเริ่มต้น",
      changes: [
        { text: "ปรับปรุงขั้นตอนติดตั้งให้ชัดเจนขึ้น", sortOrder: 1 },
        { text: "เพิ่มเอกสารตั้งค่าระบบสำหรับทีมคลังสินค้า", sortOrder: 2 },
        { text: "ปรับข้อความแจ้งเตือนในหน้าดาวน์โหลด", sortOrder: 3 },
      ],
      downloadUrl: FILE.installer,
      isLatest: true,
      sortOrder: 1,
      isActive: true,
      publishedAt: "2026-08-15T10:00:00.000Z",
    },
    {
      id: 1222,
      documentId: "mock-release-th-previous",
      name: "iStock Express Installer",
      version: "2026.7",
      releaseDate: "2026-07-18",
      summary: "เวอร์ชันก่อนหน้าสำหรับอ้างอิงรายการเปลี่ยนแปลง",
      changes: [
        { text: "ปรับปรุงประสิทธิภาพการโหลดข้อมูล", sortOrder: 1 },
        { text: "แก้ไขข้อความในรายงานบางส่วน", sortOrder: 2 },
      ],
      downloadUrl: FILE.installer,
      isLatest: false,
      sortOrder: 2,
      isActive: true,
      publishedAt: "2026-07-18T10:00:00.000Z",
    },
  ],
  en: [
    {
      id: 1231,
      documentId: "mock-release-en-latest",
      name: "iStock Express Installer",
      version: "2026.8",
      releaseDate: "2026-08-15",
      summary: "Sample download-center release with stability updates and improved onboarding documents.",
      changes: [
        { text: "Improved installer steps for clearer setup.", sortOrder: 1 },
        { text: "Added warehouse team configuration notes.", sortOrder: 2 },
        { text: "Updated download center helper messages.", sortOrder: 3 },
      ],
      downloadUrl: FILE.installer,
      isLatest: true,
      sortOrder: 1,
      isActive: true,
      publishedAt: "2026-08-15T10:00:00.000Z",
    },
    {
      id: 1232,
      documentId: "mock-release-en-previous",
      name: "iStock Express Installer",
      version: "2026.7",
      releaseDate: "2026-07-18",
      summary: "Previous sample release for changelog reference.",
      changes: [
        { text: "Improved data loading performance.", sortOrder: 1 },
        { text: "Corrected several report labels.", sortOrder: 2 },
      ],
      downloadUrl: FILE.installer,
      isLatest: false,
      sortOrder: 2,
      isActive: true,
      publishedAt: "2026-07-18T10:00:00.000Z",
    },
  ],
};

export const mockDownloadsPage: Record<"th" | "en", DownloadsPage> = {
  th: {
    heroBadge: "ดาวน์โหลด",
    heroTitle: "ศูนย์ดาวน์โหลด Ryhts",
    heroSubtitle: "รวมเอกสาร คู่มือ สเปกสินค้า และไฟล์ติดตั้งตัวอย่างสำหรับทีมที่ใช้งานสินค้า Ryhts",
    documentsTitle: "เอกสารและไฟล์ที่พร้อมดาวน์โหลด",
    documents: mockDownloadItemsByLocale.th,
    latestVersion: mockSoftwareReleasesByLocale.th[0],
    releaseNotes: mockSoftwareReleasesByLocale.th,
    seo: {
      metaTitle: "ดาวน์โหลด | Ryhts",
      metaDescription: "ดาวน์โหลดคู่มือ แคตตาล็อก สเปกสินค้า และไฟล์ติดตั้งจาก Ryhts",
      ogType: "website",
      schemaType: "CollectionPage",
    },
  },
  en: {
    heroBadge: "Downloads",
    heroTitle: "Ryhts Download Center",
    heroSubtitle: "Documents, guides, product specifications, and sample installer files for Ryhts customers.",
    documentsTitle: "Documents and files ready to download",
    documents: mockDownloadItemsByLocale.en,
    latestVersion: mockSoftwareReleasesByLocale.en[0],
    releaseNotes: mockSoftwareReleasesByLocale.en,
    seo: {
      metaTitle: "Downloads | Ryhts",
      metaDescription: "Download Ryhts guides, catalogs, product specifications, and installer files.",
      ogType: "website",
      schemaType: "CollectionPage",
    },
  },
};

// ─── Mock Support Page ────────────────────────────────────────────

export const mockSupportPage: Record<"th" | "en", SupportPage> = {
  th: {
    heroSection: {
      badge: "ศูนย์ช่วยเหลือ",
      title: "ช่วยเลือกและแก้ปัญหาริบบอนสำหรับงานพิมพ์ของคุณ",
      subtitle:
        "รวมคำถามที่พบบ่อย คู่มือการเลือกริบบอน และช่องทางติดต่อทีม Ryhts สำหรับเครื่องพิมพ์บาร์โค้ดทุกประเภท",
      faqCtaLabel: "ดูคำถามที่พบบ่อย",
      manualCtaLabel: "ดูคู่มือ",
      contactCtaLabel: "ติดต่อฝ่ายสนับสนุน",
    },
    statusCard: {
      kicker: "สถานะทีมสนับสนุน",
      title: "พร้อมให้คำแนะนำ",
      hours: "จันทร์ - ศุกร์, 08:30 - 17:30 น.",
      statusLabel: "เปิดให้บริการ",
    },
    faqSection: {
      badge: "FAQ",
      title: "คำถามที่พบบ่อย",
      subtitle: "คำตอบสั้น กระชับ สำหรับการเลือกริบบอน การสั่งซื้อ และการใช้งานกับเครื่องพิมพ์",
      emptyPrompt: "ยังไม่มีคำถามที่พบบ่อย",
      contactCtaLabel: "ถามทีม Ryhts",
    },
    faqs: [
      {
        id: 951,
        documentId: "mock-support-faq-th-1",
        question: "ควรเลือก Ribbon Wax, Wax-Resin หรือ Resin อย่างไร?",
        answer:
          "<p>หากพิมพ์ฉลากกระดาษทั่วไปให้เริ่มที่ Wax หากต้องการความทนขูดขีดเพิ่มขึ้นให้ใช้ Wax-Resin และหากเป็นฉลากฟิล์มหรืองานอุตสาหกรรมให้เลือก Resin</p>",
        category: "การเลือกสินค้า",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 952,
        documentId: "mock-support-faq-th-2",
        question: "ริบบอน Ryhts ใช้กับเครื่องพิมพ์ยี่ห้อใดได้บ้าง?",
        answer:
          "<p>ใช้งานได้กับเครื่องพิมพ์บาร์โค้ดหลายแบรนด์ เช่น Zebra, TSC, SATO, Honeywell และ Argox โดยทีมงานช่วยตรวจสอบรุ่นเครื่องก่อนสั่งซื้อได้</p>",
        category: "ความเข้ากันได้",
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 953,
        documentId: "mock-support-faq-th-3",
        question: "ต้องแจ้งข้อมูลอะไรเพื่อให้ทีมงานแนะนำสินค้าได้เร็วขึ้น?",
        answer:
          "<p>แจ้งรุ่นเครื่องพิมพ์ ขนาดริบบอน วัสดุฉลาก และลักษณะการใช้งาน เช่น โดนความร้อน โดนสารเคมี หรือใช้งานกลางแจ้ง</p>",
        category: "การขอคำแนะนำ",
        sortOrder: 3,
        isActive: true,
      },
    ],
    helpCenterSection: {
      badge: "แหล่งข้อมูล",
      title: "คู่มือและข้อมูลช่วยตัดสินใจ",
      subtitle: "เริ่มจากข้อมูลสำคัญก่อนคุยกับฝ่ายขาย เพื่อให้เลือกสินค้าได้ตรงกับงานจริง",
    },
    helpResources: [
      {
        id: 961,
        documentId: "mock-help-th-1",
        title: "คู่มือเลือกริบบอนตามวัสดุฉลาก",
        description: "สรุปการเลือกริบบอนตามชนิดฉลาก กระดาษ ฟิล์ม และฉลากพิเศษ",
        linkText: "อ่านคู่มือ",
        url: "/support/#faq-section",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 962,
        documentId: "mock-help-th-2",
        title: "เช็กลิสต์ก่อนสั่งซื้อ",
        description: "ข้อมูลที่ควรเตรียมก่อนสอบถามราคา เช่น รุ่นเครื่อง ขนาดแกน และหน้ากว้างริบบอน",
        linkText: "ดูเช็กลิสต์",
        url: "/support/#contact-section",
        sortOrder: 2,
        isActive: true,
      },
    ],
    contactSection: {
      badge: "ติดต่อ",
      title: "ติดต่อทีม Ryhts",
      addressLabel: "ที่อยู่",
      businessHoursLabel: "เวลาทำการ",
      phoneLabel: "โทรศัพท์",
      emailLabel: "อีเมล",
    },
    contactSettings: mockGlobalSetting.th,
    seo: {
      metaTitle: "ศูนย์ช่วยเหลือ | Ryhts",
      metaDescription: "คำถามที่พบบ่อย คู่มือ และช่องทางติดต่อทีม Ryhts สำหรับงานพิมพ์บาร์โค้ด",
      ogType: "website",
      schemaType: "FAQPage",
    },
  },
  en: {
    heroSection: {
      badge: "Support",
      title: "Get help choosing and troubleshooting your ribbon setup",
      subtitle:
        "Find practical answers, buying guides, and direct Ryhts support for barcode printer ribbons.",
      faqCtaLabel: "Browse FAQ",
      manualCtaLabel: "View guides",
      contactCtaLabel: "Contact support",
    },
    statusCard: {
      kicker: "Support Status",
      title: "Ready to help",
      hours: "Mon - Fri, 8:30 AM - 5:30 PM",
      statusLabel: "Available",
    },
    faqSection: {
      badge: "FAQ",
      title: "Frequently Asked Questions",
      subtitle: "Quick answers for ribbon selection, ordering, and printer compatibility.",
      emptyPrompt: "No FAQs available yet.",
      contactCtaLabel: "Ask Ryhts",
    },
    faqs: [
      {
        id: 971,
        documentId: "mock-support-faq-en-1",
        question: "How do I choose between Wax, Wax-Resin, and Resin ribbon?",
        answer:
          "<p>Use Wax for standard paper labels, Wax-Resin when you need better scratch resistance, and Resin for film labels or demanding industrial use.</p>",
        category: "Product selection",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 972,
        documentId: "mock-support-faq-en-2",
        question: "Which printer brands work with Ryhts ribbons?",
        answer:
          "<p>Ryhts ribbons work with many barcode printer brands including Zebra, TSC, SATO, Honeywell, and Argox. Our team can check your printer model before you order.</p>",
        category: "Compatibility",
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 973,
        documentId: "mock-support-faq-en-3",
        question: "What information should I prepare before contacting sales?",
        answer:
          "<p>Please share your printer model, ribbon size, label material, and usage conditions such as heat, chemicals, or outdoor exposure.</p>",
        category: "Consulting",
        sortOrder: 3,
        isActive: true,
      },
    ],
    helpCenterSection: {
      badge: "Resources",
      title: "Guides and buying resources",
      subtitle: "Start with the essentials so our team can recommend the right ribbon faster.",
    },
    helpResources: [
      {
        id: 981,
        documentId: "mock-help-en-1",
        title: "Ribbon selection by label material",
        description: "A quick guide to matching ribbon type with paper, film, and specialty labels.",
        linkText: "Read guide",
        url: "/support/#faq-section",
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 982,
        documentId: "mock-help-en-2",
        title: "Pre-order checklist",
        description: "Prepare printer model, ribbon width, core size, and label material before requesting a quote.",
        linkText: "View checklist",
        url: "/support/#contact-section",
        sortOrder: 2,
        isActive: true,
      },
    ],
    contactSection: {
      badge: "Contact",
      title: "Contact Ryhts",
      addressLabel: "Address",
      businessHoursLabel: "Business Hours",
      phoneLabel: "Phone",
      emailLabel: "Email",
    },
    contactSettings: mockGlobalSetting.en,
    seo: {
      metaTitle: "Support | Ryhts",
      metaDescription: "FAQ, guides, and contact options for Ryhts barcode ribbon support.",
      ogType: "website",
      schemaType: "FAQPage",
    },
  },
};

// ─── Mock Cookie Setting ───────────────────────────────────────────

export const mockCookieSetting: Record<"th" | "en", CookieSetting> = {
  th: {
    settings: {
      title: "เราใช้คุกกี้",
      description: "เราใช้คุกกี้เพื่อปรับปรุงประสบการณ์ วิเคราะห์การใช้งานเว็บไซต์ และนำเสนอเนื้อหาที่เหมาะสม",
      necessaryLabel: "คุกกี้จำเป็น",
      necessaryDesc: "จำเป็นต่อการทำงานพื้นฐานของเว็บไซต์",
      functionalLabel: "คุกกี้ฟังก์ชัน",
      functionalDesc: "ช่วยจดจำการตั้งค่าและปรับปรุงประสบการณ์การใช้งาน",
      analyticsLabel: "คุกกี้วิเคราะห์",
      analyticsDesc: "ช่วยให้เราเข้าใจวิธีที่ผู้เยี่ยมชมใช้งานเว็บไซต์",
      marketingLabel: "คุกกี้การตลาด",
      marketingDesc: "ใช้เพื่อแสดงเนื้อหาและโฆษณาที่เกี่ยวข้อง",
      acceptAllLabel: "ยอมรับทั้งหมด",
      rejectAllLabel: "ปฏิเสธคุกกี้เสริม",
      manageLabel: "ตั้งค่าคุกกี้",
      savePreferencesLabel: "บันทึกการตั้งค่า",
      closeLabel: "ปิด",
      privacyPolicyLabel: "นโยบายความเป็นส่วนตัว",
      cookiePolicyLabel: "นโยบายคุกกี้",
      alwaysOnLabel: "จำเป็น",
      learnMoreLabel: "เรียนรู้เพิ่มเติม",
    },
  },
  en: {
    settings: {
      title: "We use cookies",
      description: "We use cookies to improve your experience, analyze site traffic, and serve relevant content.",
      necessaryLabel: "Necessary",
      necessaryDesc: "Essential cookies for the site to function properly.",
      functionalLabel: "Functional",
      functionalDesc: "Remember preferences and improve the browsing experience.",
      analyticsLabel: "Analytics",
      analyticsDesc: "Help us understand how visitors interact with the site.",
      marketingLabel: "Marketing",
      marketingDesc: "Used to deliver relevant content and advertising.",
      acceptAllLabel: "Accept All",
      rejectAllLabel: "Reject Optional",
      manageLabel: "Cookie Preferences",
      savePreferencesLabel: "Save Preferences",
      closeLabel: "Close",
      privacyPolicyLabel: "Privacy Policy",
      cookiePolicyLabel: "Cookie Policy",
      alwaysOnLabel: "Required",
      learnMoreLabel: "Learn more",
    },
  },
};

// ─── Mock Contact Floating ─────────────────────────────────────────

export const mockContactFloating: Record<"th" | "en", ContactFloating> = {
  th: {
    isEnabled: true,
    buttonLabel: "ติดต่อเรา",
    panelTitle: "ติดต่อฝ่ายขาย Ryhts",
    panelDescription: "สอบถามสินค้า ขอใบเสนอราคา หรือให้ทีมงานช่วยเลือกรุ่นริบบอนที่เหมาะกับเครื่องพิมพ์ของคุณ",
    closeLabel: "ปิด",
    actions: [
      {
        type: "phone",
        label: "โทรฝ่ายขาย",
        description: "094-624-6649",
        url: "tel:0946246649",
        ariaLabel: "โทรหา Ryhts ที่เบอร์ 094-624-6649",
        sortOrder: 1,
        isActive: true,
      },
      {
        type: "line",
        label: "แชทผ่าน LINE",
        description: "ตอบกลับเร็วในเวลาทำการ",
        url: "https://lin.ee/xnw0e2Y",
        ariaLabel: "ติดต่อ Ryhts ผ่าน LINE",
        openInNewTab: true,
        sortOrder: 2,
        isActive: true,
      },
      {
        type: "facebook",
        label: "Facebook",
        description: "ติดตามข่าวสารและสินค้าใหม่",
        url: "https://www.facebook.com/RyhtsRibbon",
        ariaLabel: "เปิด Facebook Ryhts Ribbon",
        openInNewTab: true,
        sortOrder: 3,
        isActive: true,
      },
      {
        type: "email",
        label: "ส่งอีเมล",
        description: "sales@ryhts.com",
        url: "mailto:sales@ryhts.com",
        ariaLabel: "ส่งอีเมลหา Ryhts",
        sortOrder: 4,
        isActive: true,
      },
    ],
  },
  en: {
    isEnabled: true,
    buttonLabel: "Contact us",
    panelTitle: "Contact Ryhts Sales",
    panelDescription: "Ask about products, request a quote, or let our team recommend the right ribbon for your printer.",
    closeLabel: "Close",
    actions: [
      {
        type: "phone",
        label: "Call sales",
        description: "094-624-6649",
        url: "tel:0946246649",
        ariaLabel: "Call Ryhts at 094-624-6649",
        sortOrder: 1,
        isActive: true,
      },
      {
        type: "line",
        label: "Chat on LINE",
        description: "Fast replies during business hours",
        url: "https://lin.ee/xnw0e2Y",
        ariaLabel: "Contact Ryhts on LINE",
        openInNewTab: true,
        sortOrder: 2,
        isActive: true,
      },
      {
        type: "facebook",
        label: "Facebook",
        description: "Follow news and product updates",
        url: "https://www.facebook.com/RyhtsRibbon",
        ariaLabel: "Open Ryhts Ribbon Facebook",
        openInNewTab: true,
        sortOrder: 3,
        isActive: true,
      },
      {
        type: "email",
        label: "Email us",
        description: "sales@ryhts.com",
        url: "mailto:sales@ryhts.com",
        ariaLabel: "Email Ryhts",
        sortOrder: 4,
        isActive: true,
      },
    ],
  },
};

// ─── Mock Navigation ───────────────────────────────────────────────

export const mockNavigation: Navigation = {
  name: "Main Navigation",
  headerItems: [
    { label: "Home", url: "/" },
    { label: "About us", url: "/about" },
    { label: "Products", url: "/products" },
    { label: "Articles", url: "/articles" },
    { label: "Contact us", url: "/contact" },
  ],
  footerSections: [],
  footerLabels: {
    contactHeading: "ติดต่อฝ่ายขาย Ryhts",
    linksHeading: "Links",
    aboutHeading: "เกี่ยวกับเรา",
    newsletterHeading: "สมัครรับข่าวสาร",
    newsletterPlaceholder: "อีเมลของคุณ",
    newsletterButton: "สมัคร",
  },
  productNames: [],
  buttonLabels: {
    contactUs: "ติดต่อเรา",
    learnMore: "เรียนรู้เพิ่มเติม",
    viewAll: "ดูทั้งหมด",
    readMore: "อ่านต่อ",
    backToHome: "กลับหน้าแรก",
    callNow: "โทรเลย",
    requestQuote: "ขอใบเสนอราคา",
    download: "ดาวน์โหลด",
  },
};
